# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  reporter:
    labels:
      - "traefik.http.routers.reporter.tls.certresolver=cfresolver"
      - "traefik.http.routers.reporter.rule=Host(`reporter.flooq.io`)"

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true
