# ------------------------------------------------------------------------------------
# services
# ------------------------------------------------------------------------------------
services:
  reporter:
    build:
      context: ../../src/reporter/
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.reporter.tls=true"
      - "traefik.http.routers.reporter.entrypoints=websecure"
      - "traefik.http.services.reporter.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    environment:
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: false
