# ------------------------------------------------------------------------------------
# services
# ------------------------------------------------------------------------------------
services:
  reporter:
    environment:
      DOCS_URL: docs

    ports:
      - 8001:8000

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - 9001:9001
      - 9000:9000
    networks:
      - traefik-public
      - default
    volumes:
      - minio_data:/data

  bucket-init:
    image: minio/mc:latest
    restart: no
    entrypoint: >
      /bin/sh -c "
      until usr/bin/mc alias set m http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}; do
        echo 'Waiting for MinIO...'; sleep 2;
      done;
      /usr/bin/mc mb m/${S3_BUCKET};
      exit 0;
      "
    networks:
      - default
    depends_on:
      - minio

volumes:
  minio_data:
