# ------------------------------------------------------------------------------------
# services
# ------------------------------------------------------------------------------------
services:
  # object storage
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - 9000:9000
    expose:
      - 9001
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.nessie.tls=true"
      - "traefik.http.routers.nessie.entrypoints=websecure"
      - "traefik.http.routers.nessie.rule=Host(`minio.localtest.me`)"
      - "traefik.http.services.nessie.loadbalancer.server.port=9001"
    networks:
      - traefik-public
      - default
    volumes:
      - minio_data:/data

  # init container
  bucket-init:
    image: minio/mc:latest
    restart: no
    entrypoint: >
      /bin/sh -c "
      until usr/bin/mc alias set m http://minio:9000 ${S3_USERNAME} ${S3_PASSWORD}; do
        echo 'Waiting for MinIO...'; sleep 2;
      done;
      /usr/bin/mc mb m/${S3_BUCKET};
      exit 0;
      "
    networks:
      - traefik-public
      - default
    depends_on:
      - minio

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true

# ------------------------------------------------------------------------------------
# volumes
# ------------------------------------------------------------------------------------
volumes:
  minio_data:
