# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  minio:
    labels:
      - "traefik.http.routers.minio.tls.certresolver=cfresolver"
      - "traefik.http.routers.minio.rule=Host(`minio.flooq.io`)"

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true
