# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  minio:
    ports:
      - 9001:9001
      - 9000:9000
