# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  backend:
    labels:
      - "traefik.http.routers.pocketbase.tls.certresolver=cfresolver"
      - "traefik.http.routers.pocketbase.rule=Host(`api.flooq.io`)"
      - "traefik.http.middlewares.pb-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.pb-headers.headers.customrequestheaders.X-Forwarded-Host=api.flooq.io"
      - "traefik.http.routers.pocketbase.middlewares=pb-headers"

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true
