# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  backend:
    labels:
      - "traefik.http.routers.pocketbase.tls.certresolver=cfresolver"
      - "traefik.http.routers.pocketbase.rule=Host(`api.flooq.io`)"

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true
