services:
  # ------------------------------------------------------------------------------------
  # reverse-proxy
  # ------------------------------------------------------------------------------------
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public

# ------------------------------------------------------------------------------------
# volumes
# ------------------------------------------------------------------------------------
volumes:
  traefik-certificates:

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    name: traefik-public
    external: false
