# ------------------------------------------------------------------------------------
# services
# ------------------------------------------------------------------------------------
services:
  webapp:
    image: flooq/webapp
    build:
      context: ../../src/webapp
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - traefik-public

# ------------------------------------------------------------------------------------
# volumes
# ------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    name: traefik-public
    external: false
