# --------------------------------------------------------------------------------------
# overrides
# --------------------------------------------------------------------------------------
services:
  webapp:
    labels:
      - "traefik.http.routers.webapp.tls.certresolver=cfresolver"
      - "traefik.http.routers.webapp.rule=Host(`flooq.io`)"
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=https://api.flooq.io

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: true
