# ------------------------------------------------------------------------------------
# services
# ------------------------------------------------------------------------------------
services:
  webapp:
    build:
      context: ../../src/webapp
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.webapp.tls=true"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.rule=Host(`webapp.localtest.me`)"
      - "traefik.http.services.webapp.loadbalancer.server.port=3000"
    networks:
      - traefik-public
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=https://api.flooq.io

# ------------------------------------------------------------------------------------
# networks
# ------------------------------------------------------------------------------------
networks:
  traefik-public:
    external: false
